# Generated by Django 2.2.3 on 2020-09-02 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lists',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uniq_code', models.BigIntegerField()),
                ('time', models.TextField(default='', null=True)),
                ('u_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigIntegerField(help_text='Enter field documentati  on', primary_key=True, serialize=False)),
                ('popularity', models.FloatField(default='', null=True)),
                ('vote_count', models.BigIntegerField(default='', null=True)),
                ('video', models.BooleanField(default='', null=True)),
                ('poster_path', models.TextField(default='', null=True)),
                ('adult', models.BooleanField(default='', null=True)),
                ('backdrop_path', models.TextField(default='', null=True)),
                ('original_language', models.CharField(default='', max_length=2, null=True)),
                ('original_title', models.TextField(default='', null=True)),
                ('genre_ids', models.TextField(default='', null=True)),
                ('title', models.TextField(default='', null=True)),
                ('vote_average', models.IntegerField(default='', null=True)),
                ('overview', models.TextField(default='', null=True)),
                ('release_date', models.TextField(default='', null=True)),
                ('belongs_to_collection', models.TextField(default='', null=True)),
                ('budget', models.TextField(default='', null=True)),
                ('genres', models.TextField(default='', null=True)),
                ('homepage', models.TextField(default='', null=True)),
                ('imdb_id', models.TextField(default='', null=True)),
                ('production_companies', models.TextField(default='', null=True)),
                ('production_countries', models.TextField(default='', null=True)),
                ('revenue', models.TextField(default='', null=True)),
                ('runtime', models.TextField(default='', null=True)),
                ('spoken_languages', models.TextField(default='', null=True)),
                ('status', models.TextField(default='', null=True)),
                ('tagline', models.TextField(default='', null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='movie_bucket',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time', models.TextField(default='', null=True)),
                ('list_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_bucket.lists')),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_bucket.movie')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
