# Generated by Django 2.2.3 on 2020-08-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigIntegerField(help_text='Enter field documentati  on', primary_key=True, serialize=False)),
                ('popularity', models.FloatField(default='')),
                ('vote_count', models.BigIntegerField(default='')),
                ('video', models.BooleanField(default='')),
                ('poster_path', models.TextField(default='')),
                ('adult', models.BooleanField(default='')),
                ('backdrop_path', models.TextField(default='')),
                ('original_language', models.CharField(default='', max_length=2)),
                ('original_title', models.TextField(default='')),
                ('genre_ids', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('vote_average', models.IntegerField(default='')),
                ('overview', models.TextField(default='')),
                ('release_date', models.DateField(default='')),
                ('belongs_to_collection', models.TextField(default='')),
                ('budget', models.TextField(default='')),
                ('genres', models.TextField(default='')),
                ('homepage', models.TextField(default='')),
                ('imdb_id', models.TextField(default='')),
                ('production_companies', models.TextField(default='')),
                ('production_countries', models.TextField(default='')),
                ('revenue', models.TextField(default='')),
                ('runtime', models.TextField(default='')),
                ('spoken_languages', models.TextField(default='')),
                ('status', models.TextField(default='')),
                ('tagline', models.TextField(default='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='my_bucket',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default='')),
                ('movie_id', models.ManyToManyField(to='movie_bucket.movie')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
