# Generated by Django 2.2.3 on 2020-09-03 04:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_bucket', '0003_auto_20200903_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie_bucket',
            new_name='watch_list',
        ),
    ]
