# Generated by Django 2.2.3 on 2020-09-03 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_bucket', '0004_auto_20200903_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(default='', null=True)),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_bucket.movie')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.DeleteModel(
            name='watch_list',
        ),
    ]
